# Generated by Django 5.2.6 on 2025-09-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Engineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('project_name', models.CharField(max_length=100)),
                ('planner', models.CharField(max_length=100)),
                ('skills', models.JSONField()),
                ('engineer_status', models.CharField(max_length=20)),
                ('phase', models.CharField(max_length=100)),
            ],
        ),
    ]
