# Generated by Django 5.2.6 on 2025-10-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='email',
            field=models.EmailField(default='temp@example.com', max_length=254, unique=True),
        ),
    ]
