# Generated by Django 5.2.6 on 2025-09-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='phase',
            field=models.JSONField(),
        ),
    ]
