# Generated by hand

from django.db import migrations, models
import django.contrib.postgres.fields.jsonb

def convert_phase_to_json(apps, schema_editor):
    """既存のphase文字列データを配列に変換"""
    Engineer = apps.get_model('engineers', 'Engineer')
    for engineer in Engineer.objects.all():
        if engineer.phase:
            if isinstance(engineer.phase, str):
                # 文字列をカンマで分割して配列に変換
                phase_list = [phase.strip() for phase in engineer.phase.split(',')]
                engineer.phase = phase_list
                engineer.save()
            # すでにlistなら何もしない

def convert_phase_to_string(apps, schema_editor):
    """ロールバック用：配列データを文字列に変換"""
    Engineer = apps.get_model('engineers', 'Engineer')
    for engineer in Engineer.objects.all():
        if isinstance(engineer.phase, list):
            engineer.phase = ', '.join(engineer.phase)
            engineer.save()

class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0001_initial'),
    ]

    operations = [
        # まず、データを変換
        migrations.RunPython(convert_phase_to_json, convert_phase_to_string),
        
        # その後、フィールドタイプを変更
        migrations.AlterField(
            model_name='engineer',
            name='phase',
            field=models.JSONField(),
        ),
    ]
