# Generated by Django 5.2.6 on 2025-10-07 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_engineer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdiaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Prodiaユーザー',
                'verbose_name_plural': 'Prodiaユーザー',
            },
        ),
    ]
