# Generated by Django 5.2.6 on 2025-09-14 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0002_alter_engineer_phase'),
        ('engineers', '0002_convert_phase_to_json'),
    ]

    operations = [
    ]
