# Generated by Django 5.2.6 on 2025-10-10 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0003_prodiauser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
