# Generated by Django 5.2.6 on 2025-09-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0003_merge_20250914_1109'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='skillsheets/')),
                ('uploader', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('is_approved', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
