# Generated by Django 5.2.6 on 2025-10-11 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0004_alter_engineer_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_type', models.CharField(choices=[('customer_interview', 'お客様面談'), ('evaluation_interview', '評価面談'), ('one_on_one', '1on1面談'), ('other', 'その他')], max_length=30)),
                ('client_company', models.CharField(blank=True, max_length=200, null=True)),
                ('result', models.CharField(choices=[('pass', '合格'), ('fail', '不合格'), ('pending', '保留'), ('canceled', 'キャンセル')], max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('improvement_points', models.TextField(blank=True, null=True)),
                ('technical_skill', models.IntegerField(blank=True, help_text='技術力（1-5）', null=True)),
                ('communication_skill', models.IntegerField(blank=True, help_text='コミュニケーション力（1-5）', null=True)),
                ('motivation', models.IntegerField(blank=True, help_text='やる気・意欲（1-5）', null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('next_action', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers.prodiauser')),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='engineers.engineer')),
            ],
            options={
                'verbose_name': '面談履歴',
                'verbose_name_plural': '面談履歴',
                'ordering': ['-interview_date'],
            },
        ),
    ]
