# Generated by Django 5.2.6 on 2025-09-14 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0004_skillsheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='skillsheet',
            name='engineer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
