# Generated by Django 5.2.6 on 2025-10-13 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0005_interview'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='goals_next_period',
            field=models.TextField(blank=True, help_text='次期目標', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='improvement_areas',
            field=models.TextField(blank=True, help_text='改善領域', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='leadership',
            field=models.IntegerField(blank=True, help_text='リーダーシップ（1-5）', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='overall_rating',
            field=models.IntegerField(blank=True, help_text='総合評価（1-5）', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='problem_solving',
            field=models.IntegerField(blank=True, help_text='問題解決力（1-5）', null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='strengths',
            field=models.TextField(blank=True, help_text='強み・評価点', null=True),
        ),
    ]
