# Generated by Django 5.2.6 on 2025-09-19 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0005_skillsheet_engineer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo_type', models.CharField(choices=[('engineer', 'エンジニア個別メモ'), ('project', '案件メモ'), ('task', 'タスクメモ'), ('general', '全体メモ')], default='engineer', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('engineer_name', models.CharField(blank=True, max_length=100, null=True)),
                ('author', models.CharField(max_length=100)),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '緊急')], default='medium', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('is_completed', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_shared', models.BooleanField(default=False)),
                ('skillsheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='engineers.skillsheet')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MemoAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='memo_attachments/')),
                ('file_name', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('memo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='engineers.salesmemo')),
            ],
        ),
        migrations.AddIndex(
            model_name='salesmemo',
            index=models.Index(fields=['memo_type', 'engineer_name'], name='engineers_s_memo_ty_7bd5b9_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmemo',
            index=models.Index(fields=['author', 'created_at'], name='engineers_s_author_19fa5a_idx'),
        ),
        migrations.AddIndex(
            model_name='salesmemo',
            index=models.Index(fields=['is_completed', 'due_date'], name='engineers_s_is_comp_69aba5_idx'),
        ),
    ]
