# Generated by Django 5.2.6 on 2025-10-25 14:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0006_interview_goals_next_period_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecruitmentChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=100, verbose_name='応募者名')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='メールアドレス')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号')),
                ('channel', models.CharField(choices=[('sns_instagram', 'Instagram'), ('sns_x', 'X（Twitter）'), ('sns_tiktok', 'TikTok'), ('website', 'HP応募'), ('card_interview', 'カード面談'), ('referral', 'リファラル'), ('job_media', '求人媒体'), ('indeed', 'Indeed'), ('other', 'その他')], max_length=20, verbose_name='採用経路')),
                ('channel_detail', models.CharField(blank=True, max_length=200, null=True, verbose_name='詳細情報')),
                ('status', models.CharField(choices=[('applied', '応募'), ('screening', '書類選考中'), ('interview', '面接中'), ('hired', '採用'), ('rejected', '不採用'), ('withdrawn', '辞退')], default='applied', max_length=20, verbose_name='ステータス')),
                ('applied_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='応募日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('sns_post_url', models.URLField(blank=True, null=True, verbose_name='SNS投稿URL')),
                ('sns_engagement_data', models.JSONField(blank=True, null=True, verbose_name='エンゲージメントデータ')),
                ('hired_at', models.DateTimeField(blank=True, null=True, verbose_name='採用決定日')),
                ('cost_per_acquisition', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='採用単価')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '採用経路管理',
                'verbose_name_plural': '採用経路管理',
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialMediaPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('tiktok', 'TikTok'), ('instagram', 'Instagram'), ('x', 'X（Twitter）')], max_length=20, verbose_name='プラットフォーム')),
                ('post_id', models.CharField(max_length=100, unique=True, verbose_name='投稿ID')),
                ('post_url', models.URLField(verbose_name='投稿URL')),
                ('content', models.TextField(verbose_name='投稿内容')),
                ('hashtags', models.JSONField(blank=True, null=True, verbose_name='ハッシュタグ')),
                ('posted_at', models.DateTimeField(verbose_name='投稿日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='記録日時')),
                ('likes_count', models.IntegerField(default=0, verbose_name='いいね数')),
                ('comments_count', models.IntegerField(default=0, verbose_name='コメント数')),
                ('shares_count', models.IntegerField(default=0, verbose_name='シェア数')),
                ('views_count', models.IntegerField(default=0, verbose_name='視聴数')),
                ('impressions', models.IntegerField(default=0, verbose_name='インプレッション')),
                ('reach', models.IntegerField(default=0, verbose_name='リーチ')),
                ('engagement_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='エンゲージメント率')),
                ('applications_generated', models.IntegerField(default=0, verbose_name='応募発生数')),
                ('hires_generated', models.IntegerField(default=0, verbose_name='採用発生数')),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='最終同期日時')),
            ],
            options={
                'verbose_name': 'SNS投稿',
                'verbose_name_plural': 'SNS投稿',
                'ordering': ['-posted_at'],
            },
        ),
    ]
