# Generated by Django 5.2.6 on 2025-11-01 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0007_recruitmentchannel_socialmediapost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='engineer',
            options={'verbose_name': 'エンジニア', 'verbose_name_plural': 'エンジニア'},
        ),
        migrations.AddField(
            model_name='engineer',
            name='client_company',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='派遣先企業名'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='contract_type',
            field=models.CharField(choices=[('ses', 'SES'), ('dispatch', '派遣'), ('contract', '請負'), ('freelance', 'フリーランス'), ('internal', '社内開発')], default='ses', max_length=20, verbose_name='契約形態'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='monthly_rate',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='月単価（円）'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='monthly_revenue',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='月売上（自動計算）'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='project_end_date',
            field=models.DateField(blank=True, null=True, verbose_name='プロジェクト終了予定日'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='project_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='プロジェクト開始日'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='project_status',
            field=models.CharField(choices=[('active', '稼働中'), ('pending', '待機中'), ('ending', '終了予定'), ('ended', '終了'), ('paused', '一時停止')], default='active', max_length=20, verbose_name='プロジェクトステータス'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='revenue_updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='売上情報更新日'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='working_days_per_month',
            field=models.IntegerField(default=20, verbose_name='月稼働日数'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='working_rate',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=3, verbose_name='稼働率（0.0-1.0）'),
        ),
        migrations.CreateModel(
            name='MonthlyRevenueSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.DateField(verbose_name='対象年月（月初日）')),
                ('actual_revenue', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='実際売上（円）')),
                ('active_engineers', models.IntegerField(verbose_name='稼働エンジニア数')),
                ('total_working_days', models.IntegerField(verbose_name='総稼働日数')),
                ('average_daily_revenue', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='日平均売上')),
                ('revenue_per_engineer', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='エンジニア当たり売上')),
                ('previous_year_revenue', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, verbose_name='前年同月売上')),
                ('year_over_year_growth', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='前年同月比成長率')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '月次売上サマリー',
                'verbose_name_plural': '月次売上サマリー',
                'ordering': ['-year_month'],
                'unique_together': {('year_month',)},
            },
        ),
        migrations.CreateModel(
            name='RevenueForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forecast_date', models.DateField(verbose_name='予測対象年月')),
                ('forecast_type', models.CharField(choices=[('monthly', '月次予測'), ('quarterly', '四半期予測'), ('annual', '年次予測')], max_length=20, verbose_name='予測期間')),
                ('scenario', models.CharField(choices=[('optimistic', '楽観シナリオ'), ('realistic', '現実シナリオ'), ('pessimistic', '悲観シナリオ')], max_length=20, verbose_name='シナリオ')),
                ('total_revenue', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='総売上予測（円）')),
                ('active_engineers_count', models.IntegerField(verbose_name='稼働エンジニア数')),
                ('average_monthly_rate', models.DecimalField(decimal_places=0, max_digits=10, verbose_name='平均月単価')),
                ('average_working_rate', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='平均稼働率')),
                ('new_hires_assumption', models.IntegerField(default=0, verbose_name='新規採用想定数')),
                ('rate_increase_assumption', models.DecimalField(decimal_places=2, default=0, max_digits=3, verbose_name='単価上昇率想定')),
                ('project_continuation_rate', models.DecimalField(decimal_places=2, default=0.85, max_digits=3, verbose_name='プロジェクト継続率')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engineers.prodiauser', verbose_name='作成者')),
            ],
            options={
                'verbose_name': '売上予測',
                'verbose_name_plural': '売上予測',
                'ordering': ['-forecast_date', 'scenario'],
                'unique_together': {('forecast_date', 'forecast_type', 'scenario')},
            },
        ),
    ]
