# Generated by Django 5.2.6 on 2026-03-23 02:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0008_alter_engineer_options_engineer_client_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='企業名')),
                ('memo', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '企業',
                'verbose_name_plural': '企業一覧',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CompanyAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planner', models.CharField(max_length=100, verbose_name='プランナー')),
                ('appointment_date', models.DateField(verbose_name='日程')),
                ('appointment_time', models.TimeField(blank=True, null=True, verbose_name='時間')),
                ('status', models.CharField(choices=[('scheduled', '予定'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='scheduled', max_length=20, verbose_name='ステータス')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='engineers.company', verbose_name='企業')),
            ],
            options={
                'verbose_name': 'アポイント',
                'verbose_name_plural': 'アポイント一覧',
                'ordering': ['appointment_date', 'appointment_time'],
            },
        ),
    ]
