# Generated by Django 5.2.6 on 2026-03-31 01:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0009_company_companyappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案件タイトル')),
                ('client_company', models.CharField(max_length=200, verbose_name='客先企業名')),
                ('contact_person', models.CharField(blank=True, max_length=100, null=True, verbose_name='担当者名')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='担当者メール')),
                ('contact_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='担当者電話')),
                ('stage', models.CharField(choices=[('lead', 'リード獲得'), ('contact', '初回コンタクト'), ('proposal', '提案中'), ('interview', '面談設定'), ('negotiation', '条件交渉'), ('won', '成約'), ('lost', '失注')], default='lead', max_length=20, verbose_name='ステージ')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高'), ('urgent', '至急')], default='medium', max_length=10, verbose_name='優先度')),
                ('description', models.TextField(blank=True, null=True, verbose_name='案件詳細')),
                ('required_skills', models.JSONField(blank=True, default=list, verbose_name='必要スキル')),
                ('expected_monthly_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='想定月単価（円）')),
                ('expected_start_date', models.DateField(blank=True, null=True, verbose_name='参画予定日')),
                ('expected_duration_months', models.IntegerField(blank=True, null=True, verbose_name='想定期間（月）')),
                ('next_action', models.TextField(blank=True, null=True, verbose_name='次回アクション')),
                ('next_action_date', models.DateField(blank=True, null=True, verbose_name='次回アクション日')),
                ('win_probability', models.IntegerField(default=50, verbose_name='受注確率（%）')),
                ('assigned_to', models.CharField(max_length=100, verbose_name='担当営業')),
                ('lost_reason', models.TextField(blank=True, null=True, verbose_name='失注理由')),
                ('won_at', models.DateField(blank=True, null=True, verbose_name='成約日')),
                ('lost_at', models.DateField(blank=True, null=True, verbose_name='失注日')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('proposed_engineers', models.ManyToManyField(blank=True, related_name='deals', to='engineers.engineer', verbose_name='提案エンジニア')),
            ],
            options={
                'verbose_name': '案件',
                'verbose_name_plural': '案件一覧',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='DealActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('note', 'メモ'), ('call', '電話'), ('email', 'メール'), ('meeting', '訪問'), ('proposal', '提案書送付'), ('stage_move', 'ステージ変更')], max_length=20, verbose_name='活動種別')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_by', models.CharField(max_length=100, verbose_name='記録者')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='engineers.deal', verbose_name='案件')),
            ],
            options={
                'verbose_name': '案件活動履歴',
                'verbose_name_plural': '案件活動履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
