# Generated by Django 5.2.6 on 2026-03-31 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0010_deal_dealactivity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案件名')),
                ('client_company', models.CharField(max_length=200, verbose_name='元請企業名')),
                ('client_contact', models.CharField(blank=True, max_length=100, null=True, verbose_name='客先担当者名')),
                ('client_contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='客先担当者メール')),
                ('client_contact_phone', models.CharField(blank=True, max_length=30, null=True, verbose_name='客先担当者電話')),
                ('status', models.CharField(choices=[('active', '参画中'), ('planned', '開始予定'), ('completed', '完了'), ('suspended', '中断')], default='active', max_length=20, verbose_name='ステータス')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='案件開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='案件終了予定日')),
                ('description', models.TextField(blank=True, null=True, verbose_name='案件詳細')),
                ('required_skills', models.JSONField(blank=True, default=list, verbose_name='必要スキル')),
                ('location', models.CharField(blank=True, max_length=200, null=True, verbose_name='就業場所')),
                ('work_style', models.CharField(blank=True, choices=[('onsite', '常駐'), ('remote', 'フルリモート'), ('hybrid', 'ハイブリッド')], max_length=20, null=True, verbose_name='勤務形態')),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='月単価（会社受取）')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考・メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '元請案件',
                'verbose_name_plural': '元請案件一覧',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='参画開始日')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='参画終了予定日')),
                ('monthly_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='月単価（エンジニア）')),
                ('role', models.CharField(blank=True, max_length=100, null=True, verbose_name='役割（PL/PG等）')),
                ('is_active', models.BooleanField(default=True, verbose_name='現在参画中')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('engineer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assignments', to='engineers.engineer', verbose_name='エンジニア')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='engineers.project', verbose_name='案件')),
            ],
            options={
                'verbose_name': 'エンジニア参画情報',
                'verbose_name_plural': 'エンジニア参画情報一覧',
                'ordering': ['-start_date'],
                'unique_together': {('project', 'engineer')},
            },
        ),
    ]
