# Generated by Django 5.2.6 on 2026-04-03 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0011_project_projectassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='stage',
            field=models.CharField(choices=[('open_system', 'オープン系'), ('web', 'Web系'), ('embedded', '組み込み'), ('infrastructure', 'インフラ'), ('support_other', '開発支援・その他'), ('low_skill', 'ロースキル')], default='open_system', max_length=20, verbose_name='ステージ'),
        ),
    ]
