# Generated by Django 5.2.6 on 2026-04-03 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0012_alter_deal_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerEngineer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='技術者氏名')),
                ('name_kana', models.CharField(blank=True, max_length=100, null=True, verbose_name='フリガナ')),
                ('partner_company', models.CharField(max_length=200, verbose_name='所属会社（BP会社名）')),
                ('skills', models.JSONField(blank=True, default=list, verbose_name='スキル')),
                ('planner', models.CharField(blank=True, max_length=100, null=True, verbose_name='担当プランナー')),
                ('status', models.CharField(choices=[('active', '稼働中'), ('upcoming', '稼働予定'), ('free', 'フリー'), ('inactive', '非稼働')], default='active', max_length=20, verbose_name='ステータス')),
                ('project_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='案件名')),
                ('nearest_station', models.CharField(blank=True, max_length=100, null=True, verbose_name='最寄り駅')),
                ('remote', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無'), ('hybrid', 'ハイブリッド')], max_length=10, null=True, verbose_name='リモート有無')),
                ('contract_start', models.DateField(blank=True, null=True, verbose_name='契約開始日')),
                ('contract_end', models.DateField(blank=True, null=True, verbose_name='契約終了日')),
                ('extension_possibility', models.CharField(blank=True, choices=[('yes', '有'), ('no', '無'), ('unknown', '未定')], max_length=10, null=True, verbose_name='延長の可能性')),
                ('calendar_type', models.CharField(blank=True, default='通常カレンダー', max_length=100, null=True, verbose_name='カレンダー')),
                ('work_hours', models.CharField(blank=True, default='9:00-18:00', max_length=50, null=True, verbose_name='勤務時間')),
                ('actual_work_hours', models.CharField(blank=True, default='8h', max_length=20, null=True, verbose_name='実働時間')),
                ('client_company', models.CharField(blank=True, max_length=200, null=True, verbose_name='甲：会社名')),
                ('client_unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='甲：基本単価（円）')),
                ('client_settlement_range', models.CharField(blank=True, default='140-180h', max_length=50, null=True, verbose_name='甲：精算幅')),
                ('client_overtime_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='甲：超過単価（円）')),
                ('client_deduction_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='甲：控除単価（円）')),
                ('client_settlement_unit', models.CharField(blank=True, default='15分', max_length=20, null=True, verbose_name='甲：精算単位')),
                ('client_payment_site', models.CharField(blank=True, default='月末日締め、翌月末日支払い', max_length=100, null=True, verbose_name='甲：支払サイト')),
                ('client_timesheet_format', models.CharField(blank=True, default='現場フォーマット', max_length=100, null=True, verbose_name='甲：勤務表')),
                ('client_timesheet_collection', models.CharField(blank=True, max_length=200, null=True, verbose_name='甲：勤怠表回収方法')),
                ('client_invoice_deadline', models.CharField(blank=True, default='第2営業日まで', max_length=100, null=True, verbose_name='甲：請求書期限')),
                ('client_contact_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='甲：書類送付先 To')),
                ('client_contact_cc', models.CharField(blank=True, max_length=200, null=True, verbose_name='甲：書類送付先 Cc')),
                ('partner_unit_price', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='乙：基本単価（円）')),
                ('partner_settlement_range', models.CharField(blank=True, default='140-180h', max_length=50, null=True, verbose_name='乙：精算幅')),
                ('partner_overtime_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='乙：超過単価（円）')),
                ('partner_deduction_rate', models.DecimalField(blank=True, decimal_places=0, max_digits=8, null=True, verbose_name='乙：控除単価（円）')),
                ('partner_settlement_unit', models.CharField(blank=True, default='15分', max_length=20, null=True, verbose_name='乙：精算単位')),
                ('partner_payment_site', models.CharField(blank=True, default='月末日締め、翌月末日支払い', max_length=100, null=True, verbose_name='乙：支払サイト')),
                ('partner_timesheet_format', models.CharField(blank=True, default='現場フォーマット', max_length=100, null=True, verbose_name='乙：勤務表')),
                ('partner_timesheet_collection', models.CharField(blank=True, max_length=200, null=True, verbose_name='乙：勤怠表回収方法')),
                ('partner_invoice_deadline', models.CharField(blank=True, default='第2営業日まで', max_length=100, null=True, verbose_name='乙：請求書期限')),
                ('partner_contact_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='乙：書類送付先 To')),
                ('partner_contact_cc', models.CharField(blank=True, max_length=200, null=True, verbose_name='乙：書類送付先 Cc')),
                ('our_admin_to', models.CharField(blank=True, max_length=200, null=True, verbose_name='弊社事務担当 To')),
                ('our_admin_cc', models.CharField(blank=True, max_length=200, null=True, verbose_name='弊社事務担当 Cc')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'パートナーエンジニア',
                'verbose_name_plural': 'パートナーエンジニア一覧',
                'ordering': ['-updated_at'],
            },
        ),
    ]
