# Generated by Django 5.2.6 on 2026-04-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0013_partnerengineer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleapoRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='企業名')),
                ('phone_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='電話番号')),
                ('planner', models.CharField(max_length=100, verbose_name='プランナー名')),
                ('call_date', models.DateField(verbose_name='架電日')),
                ('result', models.CharField(choices=[('apo_taken', 'アポ取れた'), ('absent', '不在'), ('rejected', 'お断り'), ('callback', '折り返し待ち'), ('other', 'その他')], max_length=20, verbose_name='架電結果')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'テレアポ記録',
                'verbose_name_plural': 'テレアポ記録',
                'ordering': ['-call_date', '-created_at'],
            },
        ),
    ]
