# Generated by Django 5.2.6 on 2026-04-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0014_teleaporecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='project_location',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='プロジェクト所在地'),
        ),
    ]
