# Generated by Django 5.2.6 on 2026-04-08 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0015_engineer_project_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='contract_extended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='契約延長日'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='partnerengineer',
            name='contract_extended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='契約延長日'),
        ),
    ]
