# Generated by Django 5.2.6 on 2026-04-08 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0016_add_contract_extended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='登録日時'),
        ),
    ]
