# Generated by Django 5.2.6 on 2026-04-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0017_add_engineer_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engineer',
            name='planner',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
