# Generated by Django 5.2.6 on 2026-04-08 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0018_make_project_name_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='last_user_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終更新日時'),
        ),
        migrations.AddField(
            model_name='partnerengineer',
            name='last_user_updated_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終更新日時'),
        ),
    ]
