# Generated by Django 5.2.6 on 2026-04-08 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0019_add_last_user_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeleapoTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planner', models.CharField(max_length=100, verbose_name='プランナー名')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='メモ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teleapo_targets', to='engineers.company', verbose_name='企業')),
            ],
            options={
                'verbose_name': '架電ターゲット',
                'verbose_name_plural': '架電ターゲット一覧',
                'ordering': ['-created_at'],
                'unique_together': {('planner', 'company')},
            },
        ),
    ]
