# Generated by Django 5.2.6 on 2026-04-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0020_teleapotarget'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='website_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='ホームページURL'),
        ),
        migrations.DeleteModel(
            name='TeleapoTarget',
        ),
    ]
