# Generated by Django 5.2.6 on 2026-04-09 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0021_company_website_url_delete_teleapotarget'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyProjectReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_month', models.CharField(max_length=7, unique=True, verbose_name='対象年月')),
                ('idr_count', models.IntegerField(default=0, verbose_name='IDR稼働件数')),
                ('bp_count', models.IntegerField(default=0, verbose_name='BP稼働件数')),
                ('total_count', models.IntegerField(default=0, verbose_name='総数')),
                ('note', models.TextField(blank=True, default='', verbose_name='メモ')),
                ('is_auto', models.BooleanField(default=True, verbose_name='自動算出フラグ')),
                ('locked', models.BooleanField(default=False, verbose_name='確定フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '月次プロジェクトレポート',
                'verbose_name_plural': '月次プロジェクトレポート',
                'ordering': ['-year_month'],
            },
        ),
    ]
