# Generated by Django 5.2.6 on 2026-04-16 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0022_add_monthly_project_report'),
    ]

    operations = [
        migrations.CreateModel(
            name='BPProspect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='企業名')),
                ('engineer_name', models.CharField(blank=True, default='', max_length=100, verbose_name='エンジニア名')),
                ('supplier_name', models.CharField(blank=True, default='', max_length=200, verbose_name='仕入れ先名')),
                ('interview_date', models.CharField(blank=True, default='', max_length=20, verbose_name='面談日')),
                ('interview_time', models.CharField(blank=True, default='', max_length=20, verbose_name='面談時刻')),
                ('decision_date', models.CharField(blank=True, default='', max_length=20, verbose_name='回答期限')),
                ('start_month', models.CharField(blank=True, default='', max_length=20, verbose_name='開始月')),
                ('sales_price', models.CharField(blank=True, default='', max_length=50, verbose_name='販売単価')),
                ('purchase_price', models.CharField(blank=True, default='', max_length=50, verbose_name='仕入れ単価')),
                ('main_planner', models.CharField(default='', max_length=100, verbose_name='メインプランナー')),
                ('support_planners', models.JSONField(blank=True, default=list, verbose_name='サポートプランナー')),
                ('priority', models.CharField(default='中', max_length=10, verbose_name='優先度')),
                ('status', models.CharField(default='日程調整中', max_length=50, verbose_name='ステータス')),
                ('notes', models.TextField(blank=True, default='', verbose_name='備考')),
                ('interview_count', models.JSONField(blank=True, default=dict, verbose_name='面談件数')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='変更履歴')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'BP見込み',
                'verbose_name_plural': 'BP見込み',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PPInterview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('engineer_name', models.CharField(max_length=100, verbose_name='エンジニア名')),
                ('company_name', models.CharField(blank=True, default='', max_length=200, verbose_name='企業名')),
                ('interview_date', models.CharField(blank=True, default='', max_length=20, verbose_name='面談日')),
                ('interview_time', models.CharField(blank=True, default='', max_length=20, verbose_name='面談時刻')),
                ('sales_person', models.CharField(default='', max_length=100, verbose_name='営業担当')),
                ('status', models.CharField(default='日程調整中', max_length=50, verbose_name='ステータス')),
                ('start_month', models.CharField(blank=True, default='', max_length=20, verbose_name='開始月')),
                ('response_deadline', models.CharField(blank=True, default='', max_length=20, verbose_name='回答期限')),
                ('unit_price', models.CharField(blank=True, default='', max_length=50, verbose_name='単価')),
                ('notes', models.TextField(blank=True, default='', verbose_name='備考')),
                ('history', models.JSONField(blank=True, default=list, verbose_name='変更履歴')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PP営業面談',
                'verbose_name_plural': 'PP営業面談',
                'ordering': ['-created_at'],
            },
        ),
    ]
