# Generated by Django 5.2.6 on 2026-04-16 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0023_add_pp_interview_bp_prospect'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性'), ('other', 'その他')], max_length=10, null=True, verbose_name='性別'),
        ),
    ]
