# Generated by Django 5.2.6 on 2026-04-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0024_add_gender_to_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='rate_type',
            field=models.CharField(choices=[('monthly', '月単価'), ('hourly', '時給単価')], default='monthly', max_length=10, verbose_name='単価種別'),
        ),
        migrations.AlterField(
            model_name='engineer',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', '男性'), ('female', '女性')], max_length=10, null=True, verbose_name='性別'),
        ),
    ]
