# Generated by Django 5.2.6 on 2026-05-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0026_drop_nakamapuser_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerengineer',
            name='client_planner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='甲：担当プランナー'),
        ),
        migrations.AddField(
            model_name='partnerengineer',
            name='partner_planner',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='乙：担当プランナー'),
        ),
    ]
