# Generated by Django 5.2.6 on 2026-05-03 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0027_add_client_partner_planner_to_partner_engineer'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='settlement_lower',
            field=models.IntegerField(blank=True, null=True, verbose_name='精算幅 下限（h）'),
        ),
        migrations.AddField(
            model_name='engineer',
            name='settlement_upper',
            field=models.IntegerField(blank=True, null=True, verbose_name='精算幅 上限（h）'),
        ),
    ]
