# Generated by Django 5.2.6 on 2026-05-12 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engineers', '0029_add_waiting_since_to_engineer'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '新規登録'), ('update', '更新'), ('delete', '削除')], max_length=20, verbose_name='操作種別')),
                ('target_type', models.CharField(default='engineer', max_length=50, verbose_name='対象種別')),
                ('target_name', models.CharField(max_length=200, verbose_name='対象名')),
                ('user_name', models.CharField(blank=True, default='', max_length=100, verbose_name='操作ユーザー')),
                ('details', models.JSONField(blank=True, null=True, verbose_name='詳細情報')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
            ],
            options={
                'verbose_name': '操作ログ',
                'verbose_name_plural': '操作ログ',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('type', models.CharField(choices=[('important', '重要'), ('meeting', '会議'), ('other', 'その他'), ('pp', 'PP面談'), ('bp', 'BP商談'), ('google', 'Google')], default='other', max_length=20, verbose_name='種別')),
                ('date', models.CharField(max_length=10, verbose_name='日付(YYYY-MM-DD)')),
                ('time', models.CharField(blank=True, default='', max_length=5, verbose_name='開始時刻(HH:MM)')),
                ('end_time', models.CharField(blank=True, default='', max_length=5, verbose_name='終了時刻(HH:MM)')),
                ('description', models.TextField(blank=True, default='', verbose_name='説明')),
                ('assignee', models.CharField(blank=True, default='', max_length=100, verbose_name='担当者')),
                ('reminder', models.CharField(choices=[('none', 'なし'), ('5min', '5分前'), ('15min', '15分前'), ('30min', '30分前'), ('1hour', '1時間前'), ('1day', '1日前')], default='none', max_length=10, verbose_name='リマインダー')),
                ('is_recurring', models.BooleanField(default=False, verbose_name='繰り返し')),
                ('recurring_type', models.CharField(choices=[('none', 'なし'), ('daily', '毎日'), ('weekly', '毎週'), ('monthly', '毎月')], default='none', max_length=10, verbose_name='繰り返し種別')),
                ('recurring_end_date', models.CharField(blank=True, default='', max_length=10, verbose_name='繰り返し終了日')),
                ('created_by', models.CharField(blank=True, default='', max_length=100, verbose_name='作成者')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'カレンダーイベント',
                'verbose_name_plural': 'カレンダーイベント',
                'ordering': ['date', 'time'],
            },
        ),
    ]
