name: Deploy Prodia

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /var/www/my-app/prodia-app
            git pull origin main

            npm install
            npm run build

            cd /var/www/my-app/prodia-backend
            git pull origin main

            cd prodia_backend
            source ../venv/bin/activate
            pip install -r requirements.txt
            python3 manage.py migrate

            sudo systemctl restart gunicorn || true
            sudo systemctl restart nginx
